SELECT r1.FOOD_TYPE, r1.REST_ID, r1.REST_NAME, r1.FAVORITES
FROM REST_INFO r1
WHERE r1.FAVORITES = (SELECT MAX(r2.FAVORITES) FROM REST_INFO r2 WHERE r1.FOOD_TYPE = r2.FOOD_TYPE)
ORDER BY r1.FOOD_TYPE DESC