SELECT ugu.USER_ID, ugu.NICKNAME, CONCAT(ugu.CITY, ' ', ugu.STREET_ADDRESS1, ' ', ugu.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTR(ugu.TLNO, 1, 3), '-', SUBSTR(ugu.TLNO, 4, 4), '-', SUBSTR(ugu.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER ugu
JOIN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
) ugb ON ugu.USER_ID = ugb.WRITER_ID
ORDER BY ugu.USER_ID DESC