SELECT c.CAR_ID, ROUND(AVG(DATEDIFF(c.END_DATE, c.START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
GROUP BY c.CAR_ID
HAVING AVG(DATEDIFF(c.END_DATE, c.START_DATE) + 1) >= 7
ORDER BY AVERAGE_DURATION DESC, c.CAR_ID DESC;