SELECT sd.ROUTE, CONCAT(ROUND(SUM(sd.D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(sd.D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE sd
GROUP BY sd.ROUTE
ORDER BY SUM(sd.D_BETWEEN_DIST) DESC