SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fo.AMOUNT * fp.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE fo.PRODUCE_DATE >= '2022-05-01' AND fo.PRODUCE_DATE < '2022-06-01'
GROUP BY fp.PRODUCT_ID, fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID ASC
