SELECT YEAR(ed.DIFFERENTIATION_DATE) AS YEAR, (e.MAX_SIZE_OF_COLONY - ed.SIZE_OF_COLONY) AS YEAR_DEV, ed.ID
FROM ECOLI_DATA ed
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) e ON YEAR(ed.DIFFERENTIATION_DATE) = e.YEAR
ORDER BY YEAR, YEAR_DEV