SELECT hg.SCORE, he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO) hg
JOIN HR_EMPLOYEES he ON hg.EMP_NO = he.EMP_NO
WHERE hg.SCORE = (SELECT MAX(SUM_SCORE)
    FROM (
        SELECT SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO) hs)
